### PR TITLE
first pass swagger spec for the api

### PR DESCRIPTION
**Pull request by rall**

### CODE REVIEW

**Comment by amcaplan** [comment]
Nice!

When you have a chance, I'd recommend adding a Swagger-UI image to docker-compose as we've done in PRS: https://github.com/mdx-dev/prs/blob/master/docker-compose-base.yml#L13-L18 so you can get a feel for how the documentation looks.  The way you choose to organize things and write descriptions will likely change when you have a UI to see how it looks to the end user.

**Comment by rall** [comment]
+1 on swagger-ui - apparently that's all the rage. I want to merge this one as-is however

**Comment by rall** [comment]
...

**Comment by waysidekoi** [comment]
👍

**Comment by amcaplan** [comment]
Late comment: yes, @rall, I'm in complete agreement. Just a suggestion moving forward.

**Pull request merged**
